### ISSUE TITLE
[could not bind IPv6 address "::1": Cannot assign requested address] error encountered after attempting to run `service postgresql start` as postgres user in superuser mode

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#25]
![Screenshot from 2022-08-24 22-01-39](https://user-images.githubusercontent.com/14095576/186572099-9918bfc2-2e80-4ff2-a774-7a1a6d183740.png)

**Comment by TristanDamron** [comment]
Gonna close this--with the new microservice architecture, we won't run into this issue anymore.
