### ISSUE TITLE
install & configure redis

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#3]
specify tasks for installing & configuring redis in `playbook.yaml`

**Comment by TristanDamron** [comment]
Redis integration is kind of a big question mark for me at the moment. I'm not totally sure where it will fit in. I think that we should move this to geoCML 2.0 Beta and re-evaluation after the 1.0 release. In it's place, I'm going to bring #12 into this release!

**Comment by TristanDamron** [comment]
Gonna close this issue. I haven't heard of a good enough use case for Redis yet with this project.
