### ISSUE TITLE
Update CI to support new microservice architecture

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/geocml-base-deployment#45]
Our current GHA workflow publishes a single image to our container registry. We need to update this workflow to publish geocml-desktop, geocml-server, geocml-postgres, and geocml-task-scheduler (separately) to our registry.

**Comment by capsulecorplab** [comment]
If I'm reading the documentation for docker's build & push github action correctly, it doesn't look like it currently supports building multiple images in a single action https://github.com/docker/build-push-action/blob/ffe65bfc276d2ef003d5ea483a9947a8f6d408da/README.md?plain=1#L225

**Comment by TristanDamron** [comment]
This thread makes it sound possible: https://github.com/docker/build-push-action/issues/561

If it turns out that it really isn't, we can have separate actions in a single workflow that each build/push one of these services to the registry.

**Comment by TristanDamron** [comment]
@capsulecorplab is this something you could prioritize this week?

**Comment by capsulecorplab** [comment]
@TristanDamron will probably have to wait 'til Tuesday at the earliest, but yeah I can take a look. Planning on installing a new m.2 ssd this week, since my current one has kind of reached its storage limit, among other issues...

**Comment by capsulecorplab** [comment]
> @TristanDamron https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0

Nevermind, still failed https://github.com/capsulecorplab/geocml-base-deployment/actions/runs/3644633781/jobs/6154062899#step:5:113

**Comment by TristanDamron** [comment]
@capsulecorplab Yes, it's failing because our CI is set up to build only one Dockerfile (which no longer exists). The scope of this issue is to change our CI to build all geoCML containers and host them to our registry. The new Dockerfiles are in the Dockerfiles/ directory.

**Comment by capsulecorplab** [comment]
I was referring to the suggestion to remove buildkit, but that didn't work

**Comment by TristanDamron** [comment]
That's not the issue. If you read the error message, it's failing to find the old Dockerfile in the root directory because it no longer exists. 
![image](https://user-images.githubusercontent.com/6404980/206533337-11812585-1853-45fd-8514-eabff6882c3a.png)

**Comment by TristanDamron** [comment]
@capsulecorplab has there been any progress on this?

**Comment by capsulecorplab** [comment]
@TristanDamron just got my new hard drive installed with openSUSE, but ran into an issue while attempting to run a local build. Will open an issue shortly
