### ISSUE TITLE
`Service geocml-task-scheduler has neither an image nor a build context specified` encountered while attempting local build

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#47]
Following instructions in README as of 00a4ead03b50e82fd840462288cb87937c9f2448, local build yields the following error

```
$ docker-compose build
ERROR: The Compose file is invalid because:
Service geocml-task-scheduler has neither an image nor a build context specified. At least one must be provided.
```

**Comment by TristanDamron** [comment]
Try running `docker context use default`

**Comment by capsulecorplab** [comment]
Still same issue :confused:

**Comment by TristanDamron** [comment]
Which version of Docker are you using? It's possible that your current version doesn't know how to parse the compose file. It might be worth updating to see if that helps!

**Comment by capsulecorplab** [comment]
Docker version 20.10.21, build baeda1f

**Comment by TristanDamron** [comment]
Could you please send me a snippet of your docker-compose.yml file as well as the current commit hash you're using on your local copy?

**Comment by capsulecorplab** [comment]
I checkout https://github.com/geoCML/geocml-base-deployment/commit/00a4ead03b50e82fd840462288cb87937c9f2448. No changes to `docker-compose.yml`

**Comment by capsulecorplab** [comment]
Just checked out  deea516d6bda0580bdc94a95eb2c9724089717d6 and attempted to build. Same error

**Comment by TristanDamron** [comment]
The only other troubleshooting step I can think of, at this point, is to clean your docker installation. https://docs.docker.com/config/pruning/

My thought process here is that there are some cached build objects that are preventing you from building your containers. If this doesn't work, let me know and I'll slate this issue for 0.1.0

**Comment by capsulecorplab** [comment]
I've tried `docker system prune`. Same error

**Comment by TristanDamron** [comment]
Did you use the `-a` flag?

**Comment by capsulecorplab** [comment]
I'd rather not do `-a`, since that would remove docker images I need for other project. `docker system prune` already removes any dangling build caches, so `-a` shouldn't be necessary

**Comment by TristanDamron** [comment]
Just checking. Slating this for this release, I'll look at it later. Still don't see this on my machine after doing the above troubleshooting steps.

**Comment by TristanDamron** [comment]
Could you please checkout this branch and let me know if you're able to build the services? https://github.com/TristanDamron/kasm-gis-workspace/tree/explicitly-set-build-context

**Comment by capsulecorplab** [comment]
checkout out https://github.com/TristanDamron/kasm-gis-workspace/commit/15363ca43c3ef0ad9d75743407d846ce64fc7857, but and attempted to build, encountered a different error
```
$ docker-compose build
ERROR: 'network_mode' and 'networks' cannot be combined
```

**Comment by TristanDamron** [comment]
Please pull 96584fdd64f8e277699d1aad5272b9c424abb415 and try again

**Comment by capsulecorplab** [comment]
https://github.com/geoCML/geocml-base-deployment/commit/96584fdd64f8e277699d1aad5272b9c424abb415 started building, but encountered an error on
```
Step 10/12 : COPY ../build-resources/geocml-desktop/geocml-wallpaper.png /usr/share/backgrounds/geocml-wallpaper.png
ERROR: Service 'geocml-desktop' failed to build: COPY failed: forbidden path outside the build context: ../build-resources/geocml-desktop/geocml-wallpaper.png ()
```

**Comment by TristanDamron** [comment]
My bad, I forgot to update the copy paths in the Dockerfiles to use the new build context. Should be fixed with 4263c8aa34926bd0ace23fbc74db9d027ad7daf5

**Comment by capsulecorplab** [comment]
It's working!
![Screenshot from 2022-11-29 14-21-23](https://user-images.githubusercontent.com/14095576/204650544-b1fcde97-d356-4780-a60f-ffbb82d075c3.png)

It's worth noting though that it couldn't find `geocml-network` when first starting up the image with `docker-compose up`; I encountered the following error

```
$ docker-compose up
ERROR: Network geocml-network declared as external, but could not be found. Please create the network manually using `docker network create geocml-network` and try again.
```
which was resolved by running the suggested command command.

I then ran into the following issue with `geocml-task-scheduler`

```
$ docker-compose up
Creating kasm-gis-workspace_geocml-postgres_1 ... 
Creating kasm-gis-workspace_geocml-server_1   ... 
Creating kasm-gis-workspace_geocml-task-scheduler_1 ... error
Creating kasm-gis-workspace_geocml-postgres_1       ... done
Creating kasm-gis-workspace_geocml-server_1         ... done
ERROR: for kasm-gis-workspace_geocml-task-scheduler_1  Cannot create container for service geocml-task-scheduler: invalid mount config for typCreating kasm-gis-workspace_geocml-desktop_1        ... done

ERROR: for geocml-task-scheduler  Cannot create container for service geocml-task-scheduler: invalid mount config for type "bind": bind source path does not exist: /home/captainpike/repo/tristandamron/kasm-gis-workspace/persistence-layer/DBBackups
ERROR: Encountered errors while bringing up the project.
```
which I resolved by creating an empty file called `DBBackups` in the expected path.

After which I was able to run and connect to the image via VNC viewer

**Comment by TristanDamron** [comment]
I'm glad to hear it! 😄 I'll merge this testing branch into main. I am a bit surprised that you had to manually create the DBBackups directory, docker-compose should manually create an empty directory under persistence-layer if it doesn't exist. Could you please log that as another issue and I'll look into it in another PR?
