### ISSUE TITLE
update geocml-desktop base image to working geocml/ubuntu-vnc-xfce-g3

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#63]
working geocml/ubuntu-vnc-xfce-g3 published on ghcr

**Comment by capsulecorplab** [comment]
blocked on https://github.com/geoCML/ubuntu-vnc-xfce-g3/issues/2

**Comment by TristanDamron** [comment]
I'm gonna close this issue.

geocml-desktop as we currently know it will be very different in geoCML v0.2.0; it won't use this base image.
