### ISSUE TITLE
Add geoCML documentation to geocml-server

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/geocml-base-deployment#64]
**Is your feature request related to a problem? Please describe.**
The geoCML documentation is designed (like the base geoCML deployment) to be customizable. If a user's geoCML deployment has unique functionality, they will want to extend the documentation found in the geoCML/docs repository. We can expose this documentation by serving it as an HTML file via geocml-server.

**Describe the solution you'd like**
The base geoCML documentation should be added to geocml-server. A button should be added to the geoCML Server Portal allowing users to view the documentation in their browser.

**Describe alternatives you've considered**
We can host the documentation ourselves (possibly via geocml.github.io/docs) but I would prefer a usecase-specific approach to documentation.

**Additional context**
N/A

**Comment by capsulecorplab** [comment]
blocked on https://github.com/geoCML/docs/issues/11

**Comment by TristanDamron** [comment]
I've been going back and forth on this for a while and I think that maybe it's not actually necessary... We publish documentation publicly from our own repo. If a user wants to customize their docs, they can fork our docs repo and make their own amendments.
