### ISSUE TITLE
Support for immutable image

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#69]
**Is your feature request related to a problem? Please describe.**
To add support for an immutable image as to ensure installation and configuration of tools on the system can only be done via updates to the ansible playbook(s) or Dockerfile(s)

**Describe the solution you'd like**
This would require updating the base image to one that has a read-only filesystem.

**Describe alternatives you've considered**
This is currently supported in Kasm images, but Kasm has been shown to be too "heavy", thus violating the "lightweight" principle.

**Additional context**
Open issue for this feature in a base image is currently filed in https://github.com/geoCML/ubuntu-vnc-xfce-g3/issues/3, but has yet to be implemented at the time of writing (June 22, 2024).

**Comment by TristanDamron** [comment]
Closing this, geocml-desktop is going to get a huge redesign in v0.2.0 and won't use the accetto base image.
