### ISSUE TITLE
geoCML Desktop not connecting on port 80 or 10000

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#97]
**Describe the bug**
Cannot access geoCML Desktop via localhost on either port 80 or 10000

**To Reproduce**
1. clone geocml-base-deployment
2. `cd` into geocml-base-deployment
3. run `docker-compose pull`
4. run `docker-compose up`
5. visit https://localhost:80 or https://localhost:10000 in a web browser

**Expected behavior**
Should be able to connect to geoCML Desktop

**Screenshots**
![Screenshot from 2024-10-11 14-13-47](https://github.com/user-attachments/assets/7dfa51e7-24e2-47d6-8015-94f6357ce41f)
![Screenshot from 2024-10-11 14-13-53](https://github.com/user-attachments/assets/f220c8a1-c423-43fc-a39d-0b5a59435bf1)
![Screenshot from 2024-10-11 14-14-04](https://github.com/user-attachments/assets/48908547-6490-4064-96d2-f5e19c8cf1ad)
![Screenshot from 2024-10-11 14-20-09](https://github.com/user-attachments/assets/67bac616-d78d-47f4-bbdb-e39c17f75be3)
![Screenshot from 2024-10-11 14-20-17](https://github.com/user-attachments/assets/4c0b538b-3895-429c-bead-815ab9b6f5ad)
![Screenshot from 2024-10-11 14-20-36](https://github.com/user-attachments/assets/d28d2330-cd9c-42f8-9a22-3a435d4379cf)
![Screenshot from 2024-10-11 14-20-43](https://github.com/user-attachments/assets/b1bd481f-9807-41dd-861d-342206f07b87)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Brave, Firefox, Chromium

**Additional context**
Tested as of a08ff206906bd352d2c1a5fb0355b2de449ee277

**Comment by TristanDamron** [comment]
@capsulecorplab Sorry, I'm just now seeing this after a short vacation. 

How many system resources are you allocating in Docker? It looks like Python doesn't have the resources to start these geocml-desktop or gTS.

**Comment by TristanDamron** [comment]
@capsulecorplab Also, when you're running a geoCML instance locally, don't use https (:

**Comment by capsulecorplab** [comment]
> @capsulecorplab Sorry, I'm just now seeing this after a short vacation.
> 
> How many system resources are you allocating in Docker? It looks like Python doesn't have the resources to start geocml-desktop or gTS.

![Screenshot from 2024-10-27 13-47-18](https://github.com/user-attachments/assets/0e5e87e6-f444-4b43-937b-a9ee9ac8ead4)

**Comment by capsulecorplab** [comment]
> @capsulecorplab Also, when you're running a geoCML instance locally, don't use https (:

Tried both, same issue :/

**Comment by TristanDamron** [comment]
Okay, one last thing to try: could you delete the containers you pulled, then build them locally with `docker compose build`?

**Comment by capsulecorplab** [comment]
Encountered a build error 
![Screenshot from 2024-10-27 14-02-04](https://github.com/user-attachments/assets/0584f312-f112-4fe1-890e-fe26023b2bc6)

**Comment by TristanDamron** [comment]
Strange... Let me see if I can't get a Linux Mint VM up and running, I might be able to reproduce it in that environment

**Comment by TristanDamron** [comment]
I'm still not able to reproduce this... Could you try with geoCML v0.2.0 instead of v0.3.0-INDEV? https://github.com/geoCML/geocml-base-deployment/releases/tag/v0.2.0

**Comment by capsulecorplab** [comment]
Tried building off v0.2.0, but encountered a similar build error 
![Screenshot from 2024-11-13 23-41-49](https://github.com/user-attachments/assets/553506ba-5ee7-4f80-b866-58123391deef)

**Comment by TristanDamron** [comment]
Re: https://github.com/readthedocs/readthedocs.org/issues/9171#issuecomment-1122222194

Seems like a bug with your Docker version. Please update to the latest Docker.

**Comment by TristanDamron** [comment]
@capsulecorplab Hey there, got any updates on this issue?

**Comment by capsulecorplab** [comment]
Hey! Sorry for the delay. Updating Docker Engine to version 27.3.1 seemed to get me to the Xpra client page~
![Screenshot from 2024-11-24 01-31-51](https://github.com/user-attachments/assets/d5824ff7-3755-45c3-a659-cb3a37304a8d)
